ServerSignUp/Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerSignUp.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServerSignUp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerSignUp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ServerSignUp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SystemObjects;

namespace ServerSignUp.Pages {
    public class IndexModel : PageModel {
        public List<Host> hosts = new List<Host>();

        public void OnGet() {
            hosts = Database.GetHosts();
        }

        public IActionResult OnPostCustom(int Id) {
            return RedirectToPage("SignUp", new { id = Id });
        }
    }
}

ServerSignUp/Pages/Overview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SystemObjects;

namespace ServerSignUp.Pages {
    public class OverviewModel : PageModel {

        public List<SignUp> signUps = new List<SignUp>();
        public List<Host> hosts = new List<Host>();

        public void OnGet() {
            signUps = Database.GetSignUps();
            hosts = Database.GetHosts();
        }
    }
}

ServerSignUp/Pages/SignUp.cshtml.cs
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using SystemObjects;

namespace ServerSignUp.Pages {
    public class SignUpModel : PageModel {
        [BindProperty]
        public User TempUser { get; set; }

        public Host Host;
        public string ResultInfo;

        private List<Host> hosts = new List<Host>();

        public void OnGet(string id) {
            hosts = Database.GetHosts();
            int.TryParse(id, out int ID);
            Host = hosts.FirstOrDefault(hst => hst.Id == ID);
            HttpContext.Session.SetInt32("HostID", ID);
        }

        public IActionResult OnPost() {
            int? id = HttpContext.Session.GetInt32("HostID");
            hosts = Database.GetHosts();
            Host = hosts.FirstOrDefault(hst => hst.Id == id);
            List<SignUp> signUps = Database.GetSignUps();
            User newUser;

            if (Host == null) {
                ResultInfo = "An error has occured. Host is null. Please try again.";
                return Page(); //Inform user an error occured.
            }

            if (ModelState.IsValid) {
                List<User> users = Database.GetUsers();
                newUser = users.FirstOrDefault(usr => usr.Email == TempUser.Email);

                if (newUser == null) {
                    Database.AddUser(TempUser);
                    users = Database.GetUsers();
                    newUser = users.FirstOrDefault(usr => usr.Email == TempUser.Email);
                }
            } else {
                ResultInfo = "Not all information has been entered correctly.";
                return Page();
            }

            if (Database.CanServerBeAddedTo(Host)) {
                Database.CreateSignUp(Host, newUser, "");
                return RedirectToPage("Completed");
            }

            ResultInfo = "Server is currently full, please try a different host.";
            return Page();
        }
    }
}

ServerSignUp/Pages/Completed.cshtml
@page
@model ServerSignUp.Pages.CompletedModel
@{
}

<h1>Congratulations! You have successfully signed up.</h1>

ServerSignUp/Pages/Index.cshtml
@page
@model IndexModel
@using SystemObjects;
@{
    ViewData["Title"] = "Home page";
}

<html>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Server Sign Up</title>

    <link href="~/css/ButtonStyles.css" rel="stylesheet" type="text/css" />
    <link href="~/css/HomeStyles.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <div class="Intro">
        <h1>Welcome to Server Sign Up</h1>
        <p>Please Select a Server Below to Begin the Sign Up Process</p>
    </div>
    <div class="hostContainer">
        @foreach (Host h in Model.hosts)
        {
            <form asp-page-handler="Custom" method="post" asp-route-Id="@h.Id">
                <button class="host">@h.Name</button>
            </form>
        }
    </div>
</body>
</html>

ServerSignUp/Pages/Overview.cshtml
@page
@model ServerSignUp.Pages.OverviewModel
@using SystemObjects;
@{
}

<link href="~/css/TableStyles.css" rel="stylesheet" type="text/css" />

@{

    foreach (Host host in Model.hosts)
    {

        <h1>@host.Name</h1>
        foreach (SignUp sign in Model.signUps)
        {
            if (host.Id == sign.Host.Id)
            {
                <div class="TableContainer">

                <table>
                    <tr>
                        <th>First Name</th>
                    </tr>
                    <tr>
                        <td>@sign.User.FirstName</td>
                    </tr>
                    <tr>
                        <th>Last Name</th>
                    </tr>
                    <tr>
                        <td>@sign.User.LastName</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                    </tr>
                    <tr>
                        <td>@sign.User.Email</td>
                    </tr>
                </table>
                </div>
                @*<h4>@sign.User.FirstName</h4>
                    <h4>@sign.User.LastName</h4>
                    <h4>@sign.User.Email</h4>*@
            }
        }
    }

}

ServerSignUp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Server Sign Up</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Server Sign Up</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Overview">Overview</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Server Sign Up Courtesy of RoboHost Inc
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ServerSignUp/Pages/SignUp.cshtml
@page
@model ServerSignUp.Pages.SignUpModel
@{
}


@{
    <head>
        <link href="~/css/FormStyles.css" rel="stylesheet" type="text/css" />

    </head>


    if (Model.Host == null) {
        <h1>An Error has Occured.</h1>
    } else {
        <h1>You've chosen to sign up with the group: @Model.Host.Name</h1>
        <br/>
        <br/>
        <h3>@Model.ResultInfo</h3>        
        <form method="post">
            <div>
                <label asp-for="TempUser.FirstName"></label>
                <div >
                    <input asp-for="TempUser.FirstName" class=" form-control" />
                    <span asp-validation-for="TempUser.FirstName" class="text-danger"></span>
                </div>
                <label asp-for="TempUser.LastName"></label>
                <div>
                    <input asp-for="TempUser.LastName" class=" form-control" />
                    <span asp-validation-for="TempUser.LastName" class="text-danger"></span>
                </div>
                <label asp-for="TempUser.Email"></label>
                <div>
                    <input asp-for="TempUser.Email" class=" form-control" />
                    <span asp-validation-for="TempUser.Email" class="text-danger"></span>
                </div>
                <label asp-for="TempUser.Phone"></label>
                <div>
                    <input asp-for="TempUser.Phone" class=" form-control" />
                    <span asp-validation-for="TempUser.Phone" class="text-danger"></span>
                </div>
            </div>

            <div>
                <div>
                    <button class="btn btn-primary" id="SignUP">Sign Up</button>
                </div>
            </div>
        </form>
    }
}
@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}